### ISSUE TITLE
Use package config file for API key

### ISSUE THREAD

**Issue by ejunker** [ryanwinchester/laravel-hubspot-api#1]
It would be really nice if you could add a config file for this package which could be used to store the API key. See http://laravel.com/docs/packages#package-configuration

Your advice to edit `/vendor/fungku/laravel-hubspot/src/config/api.php` is very bad. You should never edit files under /vendor since those could be overwritten when you do a composer update.

**Comment by ejunker** [comment]
I see now that you do have a package config file but didn't have any instructions on how to use it. I ran this command to publish the config file: `php artisan config:publish fungku/laravel-hubspot`. You should update your README

**Comment by ryanwinchester** [comment]
This is a problem from when I recently changed this package to use [fungku/hubspot](https://github.com/fungku/hubspot) package.

fungku/hubspot should be framework agnostic so I can't include laravel `Config` in the constructor and will need to fix that soon. (i.e. hopefully this week).

However, in the meantime you can still use environment variables, which are very easy to set in Laravel.

See: http://laravel.com/docs/configuration#protecting-sensitive-configuration

**Comment by ryanwinchester** [comment]
Or wait, I think I already did fix this in [this commit](https://github.com/fungku/laravel-hubspot-api/commit/3f944d1e22918eb5e290f0f1f27f234494d41f9a)
