### ISSUE TITLE
Namespace issue in HubSpotException

### ISSUE THREAD

**Issue by ejunker** [ryanwinchester/laravel-hubspot-api#2]
This is actually an error for `fungku/hubspot` but that repo doesn't have an issue tracker.

`PHP Fatal error:  Class 'Fungku\HubSpot\API\Exception' not found in vendor/fungku/hubspot/src/Fungku/HubSpot/API/HubSpotException.php on line 29`

Looks like you need to put a backslash () before Exception so it knows to look in the global namespace:
`class HubSpotException extends \Exception {}`

**Comment by ryanwinchester** [comment]
Good catch. I added issues to `fungku/hubspot`

Also @jlabresh1 fixed this in https://github.com/fungku/hubspot/pull/1
