### ISSUE TITLE
Laravel 5.2

### ISSUE THREAD

**Issue by cclass** [ryanwinchester/laravel-hubspot-api#4]
Starting a project with Laravel 5.2 and would like to use your HubSpot wrapper but I'm having some trouble

I've added `Fungku\HubSpot\HubSpotServiceProvider::class` to the providers list in app/config.php but receive this exception: `Call to undefined method [package]`.

I also noticed that running `$ php artisan config:publish fungku/laravel-hubspot` does not create a config file in the location specified by the docs (assuming this is because of the laravel version)

Any tips, if possible, to get this working in Laravel 5.2?

Cheers

Chris

**Comment by ryanwinchester** [comment]
I will look at it this week.

It should be too hard to update.

**Comment by ejunker** [comment]
I ran into this same issue. Trying to use it with Laravel 5.2

**Comment by gpassarelli** [comment]
@ryanwinchester, Could you please have a look into my PR?
Thanks

**Comment by ryanwinchester** [comment]
thanks @gpassarelli
